server:
  port: 9786

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

management:
  health:
    circiutbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
    env:
      enabled: true

info:
  app:
    name: Price and Inventory Service
    description: Price and Inventory Service App
    version: 0.0.1

