spring:
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default-schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 123456

server:
  port: 9788

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
    env:
      enabled: true

info:
  app:
    name: Product Service
    description: Product Service App
    version: 0.0.1

---

spring:
  config:
    activate:
      on-profile: stage
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default-schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: 123456

server:
  port: 9788

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
    env:
      enabled: true

info:
  app:
    name: Product Service
    description: Product Service App
    version: 0.0.1

