version: "3.1"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13.6-alpine
    volumes:
      - ./postgres_dev:/data/postgres
    networks:
      - integration-network-backend
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - "../data/redis:/var/lib/redis/data"
    networks:
      - integration-network-backend
    expose:
      - 6379
    ports:
      - "6379:6379"

  zipkin:
    container_name: zipkin
    hostname: zipkin
    image: openzipkin/zipkin-slim
    networks:
      - integration-network-backend
    expose:
      - 9411
    ports:
      - 9411:9411

  keyclock:
    image: quay.io/keycloak/keycloak:22.0.1
    networks:
      - integration-network-backend
    expose:
      - 8181
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev

networks:
  integration-network-backend:
volumes:
  postgres_dev: