spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: default
    import: "optional:configserver:http://localhost:8088"

---

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: stage
    import: "optional:configserver:http://config-service:8088"