server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: price-and-inventory-service
          uri: lb://price-and-inventory-service
          predicates:
            - Path=/api/v1/price-and-inventory/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/realms/spring-boot-microservices-realm"