spring:
  application:
    name: price-and-inventory-service
  config:
    import: "optional:configserver:http://localhost:8088"
    activate:
      on-profile: default

---

spring:
  application:
    name: price-and-inventory-service
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: stage
